### ISSUE TITLE
Skip custom ranges with config.ini.php

### ISSUE THREAD

**Issue by ThaDafinser** [RegioneER/RerUserDates#10]
I dont know since when it's possible, but you can exclude the custom range by a ini setting.

See here
https://github.com/ThaDafinser/Piwik-PerformanceInfo/blob/master/Controller.php#L175-L176

**Comment by tassoman** [comment]
Looks like since april-may 2014
http://issues.piwik.org/5037

**Comment by tassoman** [comment]
Using ini settings you'll exclude ranges to all the users (superadmins too). 
Using RerUserDates plugin superadmins still able to manage ranges.

**Comment by ThaDafinser** [comment]
You are right... still makes sense.
