### ISSUE TITLE
migrate Translations to Weblate

### ISSUE THREAD

**Issue by Findus23** [RegioneER/RerUserDates#17]
"fixes" #11

Hi,

We are currently in the process of moving all Matomo Translations from Transifex to Weblate (see matomo-org/matomo#17907). This makes it easier for people to contribute translations, makes the process of syncing them back into the source simpler and means that we are now using Free Software for this.

We will create a Pull Request that contributes all data on Transifex up to today into this repository.

If you are interested, we can migrate this plugin to Weblate allowing people to continue to translate the strings of this plugin in their languages.
@tassoman, just comment and we can create the component on Weblate and set things up, so you automatically get pull requests containing the updated translations whenever they change.

**Comment by tassoman** [comment]
Weblate migration is fine. Should I configure some Github bot inside this repository?

**Comment by Findus23** [comment]
Hi,

I created the component at https://hosted.weblate.org/projects/matomo/communityplugin-reruserdates/

So, soon Weblate should create a pull request adding the new languages and potential changes. From then on Weblate will create (or update) a PR whenever someone updates the translations (which you can e.g. merge before releases).

The only thing you need to do (to keep weblate up-to-date on changes on your end) is to set up a webhook using https://hosted.weblate.org/hooks/github/ as the Payload URL and keep the rest of the settings at the default

**Comment by tassoman** [comment]
I've merged PR #19  and set the webhook.
Thank you for supporting!
