### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by gaumondp** [RegioneER/RerUserDates#2]
This is my pseudo pull request as a non-coder...
;)

/lang/fr.json

{
    "RerUserDates": {
        "SuperuserMessage": "Les utilisateurs réguliers ne peuvent sélectionner de plages de dates dans les tableaux de bord ou dans leur profile (RerUserDates)",
        "DefaultDateMessage": "La plage de dates par défaut est automatiquement mise sur 'hier' puisque les plages de dates sont désactivées"
    }
}

**Comment by tassoman** [comment]
@gaumondp  we need a :fr: french translation revision after plugin release v1.2.x
Hope to hear back from you soon, let's keep in touch :sos:

**Comment by gaumondp** [comment]
I don't understand, my French translation is newer than the english file and I don't see any recent changes to /lang/en.json

Am I missing something ?

**Comment by tassoman** [comment]
Yup! :stuck_out_tongue_winking_eye: 
You're right, I've finally merged in 0985b9c6fa9a40097579769571d50d51b12308bd
So sorry for misunderstanding!
