### ISSUE TITLE
Superuser: change Report to load by default not possible

### ISSUE THREAD

**Issue by ThaDafinser** [RegioneER/RerUserDates#5]
```
Regular users are forbidden to choose a ranged default value in their profile. 
Ranged values are forced to 'yesterday' (RerUserDates)`
```

Wanted to change `Report to load by default` to `All Websites dashboard`

Inside `User settings`

**Comment by tassoman** [comment]
I'm missing the second string you'd like to be changed, can you better explain this issue?

**Comment by ThaDafinser** [comment]
Puh...need to get into it again some time, cant remember it anymore :)

**Comment by tassoman** [comment]
Just closing, feel free to open another issue if you can remember again.
No worries about it. :rainbow:
