### ISSUE TITLE
Drop backward compatibility with Piwik < v.2.4.0

### ISSUE THREAD

**Issue by tassoman** [RegioneER/RerUserDates#7]
Just wondering about settings compatibility as requirement

https://github.com/RegioneER/RerUserDates/blob/master/RerUserDates.php#L112-L116
https://github.com/RegioneER/RerUserDates/blob/master/Settings.php#L38-L42

**Comment by gaumondp** [comment]
Well, Piwik < 2.8 have security issues...
Ref: http://piwik.org/changelog/piwik-2-8-0/

So keeping you plugin compatibility with Piwik 2.8 and up is enough in theory...

**Comment by tassoman** [comment]
I agree, flawless :+1:

**Comment by tassoman** [comment]
Closed with cdf69a1737124755e272f530948eeaa866caab11 after merge, thank you to @ThaDafinser :+1:
